### ISSUE TITLE
Organize markup of Headline component

### ISSUE THREAD

**Issue by suefrontend** [suefrontend/match-headline-and-thumbnail-react#6]

**Comment by MThabsheer7** [comment]
Hey @suefrontend could you assign me?

**Comment by suefrontend** [comment]
Hi @MThabsheer7 thanks for your comment. I was planning to complete the project by myself since this is going to be on my portfolio website. But I'd love to work on other projects with you!

**Comment by MThabsheer7** [comment]
Oh cool! I am looking forward to work with you. Cheers
